version: '1.0'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: development
    # command: ["ng", "serve", "--host", "0.0.0.0", "--disableHostCheck", "true"]
