name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Make script executable
        run: chmod +x build_and_push.sh
      - name: Run script to build and push images
        run: ./build_and_push.sh
