name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Make script executable
        run: chmod +x ./build_and_push.sh

      - name: Run script to build and push images
        run: ./build_and_push.sh
      
      - name: Delete old repository from VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /home/artik3314/project
        
      - name: Clone or update repository from Github
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git clone https://github.com/artemovsergey/React.git /home/artik3314/project/
            

    
      - name: Deploy docker-compose to VPS
        uses: appleboy/ssh-action@master
        with:
              host: ${{ secrets.VPS_HOST }}
              username: ${{ secrets.VPS_USERNAME }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
                chmod +x /home/artik3314/project/vps.sh
                /home/artik3314/project/vps.sh