name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:


      - name: Connect to VPS via SSH and execute command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker ps
